### ISSUE TITLE
Logic/Program not running

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#58] opened 2019-01-05 12:50 UTC
There is one device that encounter this. I will email the .bin, .json and modbus .csv for this.
Other device that has been using the same file has no such issue.

For quick measure, I would like to request for 4 new X1 device to be installed and bring back these faulty units. It's very urgent as the hospital rooms testing is on-going at the moment. It requires our logic to work and control the equipment.

@thyong-adft @LOKJK

**Comment by thyong-adft** [comment] 2019-01-05 16:46
Dear KS,

We do not have any more new X1 in KL stock. The upcoming will arrive at KL in the end of Jan.

Best is to bring back to office to reload the config.bin or modbus.csv.

Regards,
TH Yong
Operations Manager
Mobile: +6016 417 1163

**Comment by kslee911** [comment] 2019-01-06 11:40
Hi,

If that's the case, will it be okay if i only bring new SD card (pre-loaded
with working firmware), then swap and bring back the SD card that has
problem at site to office?
Will it be the same?

Best Regards,

*KS Lee*
*Asst. Project Manager*
ADF Technologies Sdn. Bhd.
Mobile: +6016 262 1163
Email: kslee@adftech.com.my

**Comment by kslee911** [comment] 2019-01-07 00:13
KS,

Let me confirm with you by today.

Regards,
TH Yong
Operations Manager
Mobile: +6016 417 1163

**Comment by fakhrul-omar** [comment] 2019-01-16 03:58
Is this one still ongoing or @david-glover already looked at/fixed it?

**Comment by david-glover** [comment] 2019-01-16 04:26
Caused by program crashing.  (Modbus writing did not close queue, crashed for having too many file descriptors open.)
Should be fixed by c6896c6fba5c0049c19201068dadf8dd165d2146

**Closed as completed by david-glover** 2019-01-16 04:26 UTC
Labels: bug
