### ISSUE TITLE
Program became "Idle" after "Running" with no error for a few hours

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#56] opened 2019-01-05 12:37 UTC
The logic program became idle after running with no errors. 

Does power reset will set the program property status to "Idle" each time the device is powered up again from power failure?

@thyong-adft @LOKJK

**Comment by fakhrul-omar** [comment] 2019-01-16 04:03
Feels like I'm spamming the comment section now. As far as I know, there's no idle state (it stops running) for logic/chiller section. As for the program status, since it's linked to whether logic runs or not, I would say it'll show "Running", the same as reboot. Unless logic JSON is missing/disappeared.

**Comment by david-glover** [comment] 2019-01-16 05:14
The state should be the same after power up as before.
Should be fixed by fixing non-related modbus writing bug, should be caused by program crashing before saving config file, therefore the program state is not running in config when it restarts.
fixed by https://github.com/ADFTech/xtec-uc-ip-main/commit/c6896c6fba5c0049c19201068dadf8dd165d2146

**Closed as completed by david-glover** 2019-01-16 05:14 UTC
Labels: bug
